version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-container-gac
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network

  app:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DATABASE_NAME=${MYSQL_DATABASE}
    networks:
      - app-network
    command: >
      sh -c "
      npm install &&
      npm run build &&
      npm run start:dev
      "

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: